### ISSUE TITLE
Notify the Activity when Download completed

### ISSUE THREAD

**Issue by z-zghiba** [novoda/novoda#20]
There is a way to notify Activity when download complete

**Comment by blundell** [comment]
excellent I've been waiting for the way!

**Comment by xrigau** [comment]
![](https://hugelolcdn.com/hugereaction.com/i/6294.gif)

**Comment by xrigau** [comment]
![6294](https://cloud.githubusercontent.com/assets/1626673/16309578/7a996768-3969-11e6-9d60-d029b8fcb2b6.gif)

**Comment by Dorvaryn** [comment]
@z-zghiba Did you mean to open an issue on https://github.com/novoda/download-manager ?

**Comment by z-zghiba** [comment]
Yes!!
I just saw that I 'm not in the right project
I'll post it in download-manager
