### ISSUE TITLE
Release Process Template

### ISSUE THREAD

**Issue by Mecharyry** [novoda/novoda#44]
### Problem
There should be a template that can be used as a base for all Novoda Open Source projects in terms of how contributors should go about creating a release. 

### Potential Solution
Added an example template that can be iterated upon based on the discussion here:

https://github.com/novoda/novoda/wiki/Version-Release-Template

![screen shot 2017-12-14 at 10 56 54](https://user-images.githubusercontent.com/3380092/33988861-a148b308-e0bd-11e7-962d-892819dcf141.png)

**Comment by rock3r** [comment]
Maybe could take out the Merlin references from the wiki? :)

**Comment by rock3r** [comment]
Other than that, 💯

**Comment by Mecharyry** [comment]
Sure thing @rock3r, I'll remove the references to `Merlin` and keep it generic 😃

**Comment by Mecharyry** [comment]
@rock3r updated to remove `Merlin` 😄

**Comment by Mecharyry** [comment]
Asked for feedback multiple times. A couple of additional issues have been raised in relation to this: 
https://github.com/novoda/novoda/issues/47
https://github.com/novoda/novoda/issues/48

Addressed as no more feedback given.
